language: node_js
node_js:
  - lts/*
  - node
before_deploy: npm run build
deploy:
  - name: prod
    skip_cleanup: true
    provider: firebase
    token:
      secure: $FIREBASE_TOKEN
    project: $FIREBASE_PROJECT
    on:
      branch: master
      node_js: lts/*
  - name: stg
    skip_cleanup: true
    provider: firebase
    token:
      secure: $FIREBASE_TOKEN
    project: $FIREBASE_PROJECT_STG
    on:
      branch: dev
      node_js: lts/*
